### ISSUE TITLE
Unity.AspNet.WebApi, Version=5.0.2.17,Unity.Abstractions, Version=2.0.2.67

### ISSUE THREAD

**Issue by ghd258** [unitycontainer/aspnet-webapi#3]
错误	CS1705	标识为“Unity.AspNet.WebApi, Version=5.0.2.17, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f”的程序集“Unity.AspNet.WebApi”所使用的“Unity.Abstractions, Version=2.0.2.67, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f”版本高于所引用的标识为“Unity.Abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f”的程序集“Unity.Abstractions”	VOCs.WebAPI	H:\WebAPI\App_Start\UnityWebApiActivator.cs	17	活动的

**Comment by axelgenus** [comment]
Can you please provide a description in English?

**Comment by ghd258** [comment]
解决
